import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Display from "../Components/Display/Display";
import PlaceInput from "../Components/PlaceInput/PlaceInput";
import Answers from "../Components/Answers/Answers";
import GuessButton from "../Components/GuessButton/GuessButton";
import Header from "../Components/Header/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Isradle</title>
        <meta
          name="Know israel better"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Display />
        <Answers />
        <PlaceInput />
        <GuessButton />
        {/* <Bottom/> */}
      </main>

      <footer className={styles.footer}>
        <div>Contact Us</div>
        <div>Created by wordle-generator</div>
      </footer>
    </div>
  );
}
