import Head from "next/head";
import { useEffect, useState } from "react";
import Answers from "../Components/Answers/Answers";
import Display from "../Components/Display/Display";
import GuessButton from "../Components/GuessButton/GuessButton";
import Header from "../Components/Header/Header";
import PlaceInput from "../Components/PlaceInput/PlaceInput";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [place, setPlace] = useState(null);
  // const [input, setInput] = useState(null);
  const [placesNames, setPlaceNames] = useState([]);
  const [answers, setAnswers] = useState(["", "", "", "", "", ""]);
  const [gameOver, setGameOver] = useState(false);
  const [playerWon, setPlayerWon] = useState(false);
  // const [status, setStatus] = useState("run");
  // console.log(input);
  console.log("gameOver", gameOver);
  console.log("playerWon", playerWon);

  useEffect(() => {
    function fetchPlace() {
      fetch("/api/place")
        .then((res) => res.json())
        .then(({ place, placesNames }) => {
          setPlace(place);
          setPlaceNames(placesNames);
        })
        .catch((err) => {
          console.log(err);
        });
    }
    fetchPlace();
  }, []);

  return (
    <>
      <Head>
        <title>Isradle</title>
        <meta
          name="Know israel better"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {!!place ? (
        <Display place={place} playerWon={playerWon} gameOver={gameOver} />
      ) : (
        <p>Loading Riddle...</p>
      )}
      <div className={styles.container}>
        {!!place ? (
          <Answers answers={answers} place={place} playerWon={playerWon} />
        ) : (
          <p>Loading Riddle...</p>
        )}
        <main className={styles.main}>
          {!gameOver && placesNames.length && (
            <PlaceInput
              placesNames={placesNames}
              setAnswers={setAnswers}
              answers={answers}
              setPlayerWon={setPlayerWon}
              setGameOver={setGameOver}
              place={place}
              // setInput={setInput}
            />
          )}
        </main>
        <footer className={styles.footer}>
          <div>Contact Us</div>
          <div>Created by wordle-generator</div>
        </footer>
      </div>
    </>
  );
}
